### ISSUE TITLE
Number Values missing (Double) 

### ISSUE THREAD

**Issue by coaster3000** [Ranzdo/MethodCommand#3]
Double handler is missing. I could attempt to create one and request a pull from you. But i just want inform you at the moment. I am going to work on this now after i post this. I will post comment if i fail to create it..

How i know...

se.ranzdo.bukkit.methodcommand.RegisterCommandMethodException: Could not register the command method modifySP in the class net.terra.points.command.StratPointCommand. Reason: Could not find a ArgumentHandler for (double)
at se.ranzdo.bukkit.methodcommand.RegisteredCommand.getArgumenHandler(RegisteredCommand.java:130)
at se.ranzdo.bukkit.methodcommand.RegisteredCommand.set(RegisteredCommand.java:300)
at se.ranzdo.bukkit.methodcommand.CommandHandler.registerCommands(CommandHandler.java:217)

It is a double parameter. Instead of int.

**Comment by coaster3000** [comment]
I think i got it complete. Quite simple when you already have one number value already done..

**Comment by coaster3000** [comment]
Sorry about double Post
